data_eng/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls)
    , path('', TemplateView.as_view(template_name='home.html'), name='home')
    # , path('dataeng/', include('dataeng.urls'))
    , path('rover/', include('rover.urls'), name='rover')
    , path('accounts/', include('django.contrib.auth.urls'))
    ,
]

if settings.DEBUG:  # remember to set 'DEBUG = True' in settings.py
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dataeng/urls.py
from django.urls import path
from .views import TasksView, createTask, refreshTask, refreshTaskStatus

urlpatterns = [
    path('', TasksView.as_view(), name='tasks')
    , path('<int:id>/push', refreshTask, name='task_push')
    , path('<int:id>/status', refreshTaskStatus, name='task_status')
]

rover/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('dagtask/', DagTask.as_view(), name='dagtask')
    , path('dagtask/create/', DagTaskCreate.as_view(), name='dagtask_create')
    , path('dagtask/<pk>/', DagTaskView.as_view(), name='dagtask_view')
    , path('dagtask/<int:pk>/push/', dagTaskPush, name='dagtask_refresh')
    , path('dagrun/<int:pk>/status/', dagTaskStatus, name='dagtask_status')
]

dataeng/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from django.core.exceptions import ValidationError
import os
from django.utils.deconstruct import deconstructible
from simple_history.models import HistoricalRecords

# Create your models here.

@deconstructible
class PathAndRename(object):
    # https://stackoverflow.com/questions/25767787/django-cannot-create-migrations-for-imagefield-with-dynamic-upload-to-value
    def __init__(self, path, prefix):
        self.path = path
        self.prefix = prefix
    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        filename = f'{self.prefix}/{instance.task}/{datetime.now():%Y%m%d%H%M%S}.{ext}'
        return os.path.join(self.path, filename)

def validate_for_csvfile_type(value):
    # https://stackoverflow.com/questions/6460848/how-to-limit-file-types-on-file-uploads-for-modelforms-with-filefields
    # print(value.file.content_type)
    accepted_file_types = ['application/vnd.ms-excel', 'text/plain', 'text/x-csv']
    if value.file.content_type not in accepted_file_types:
        raise ValidationError(f'content type of file has to be either of {",".join(accepted_file_types)}')

path_and_rename = PathAndRename('dataeng', 'tasks')

class DataEng(models.Model):
    id = models.AutoField(primary_key=True)
    task = models.ForeignKey('TaskName', on_delete=models.SET_NULL, null=True)
    params = models.CharField(max_length=100)
    attachment = models.FileField(upload_to=path_and_rename, validators=[validate_for_csvfile_type])
    # pushed = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    refreshed_at = models.DateTimeField(null=True, blank=True)
    message = models.CharField(max_length=500, null=True, blank=True)
    task_scheduled_id = models.CharField(max_length=100, null=True, blank=True)
    task_scheduled_status = models.CharField(max_length=500, null=True, blank=True)
    history = HistoricalRecords()


    def __str__(self):
        return f"{self.task}, {self.params}"

    class Meta:
        verbose_name = "Task Upload"
        verbose_name_plural = "Task Uploads"
        ordering = ['-created_at']

    def delete(self, *args, **kwargs):
        self.attachment.delete()
        super().delete(*args, **kwargs)

class TaskName(models.Model):
    id = models.AutoField(primary_key=True)
    task_name = models.CharField(max_length=100)
    created_ts = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.task_name
    
    class Mets:
        verbose_name = "Task Name"
        verbose_name_plural = "Task Names"

rover/models.py
from django.db import models
from django.utils import timezone
from simple_history.models import HistoricalRecords
from django.utils.deconstruct import deconstructible
from django.core.exceptions import ValidationError
import os
from datetime import datetime

# Create your models here.

@deconstructible
class PathAndRename():
# https://stackoverflow.com/questions/25767787/django-cannot-create-migrations-for-imagefield-with-dynamic-upload-to-value
    def __init__(self, path, prefix):
        self.path = path
        self.prefix = prefix
    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        filename = f'{self.prefix}/{instance.dag_file}/{datetime.now():%Y%m%d%H%M%S}.{ext}'
        return os.path.join(self.path, filename)

def validate_for_csvfile_type(value):
    # https://stackoverflow.com/questions/6460848/how-to-limit-file-types-on-file-uploads-for-modelforms-with-filefields
    # print(value.file.content_type)
    accepted_file_types = ['application/vnd.ms-excel', 'text/plain', 'text/x-csv']
    if value.file.content_type not in accepted_file_types:
        raise ValidationError(f'content type of file has to be either of {",".join(accepted_file_types)}')

path_and_rename = PathAndRename('rover', 'dags')

class DAG(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    file_list = models.ManyToManyField('Dag_File')

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "DAG"
        verbose_name_plural = "DAGS"

class Dag_File(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Dag File"
        verbose_name_plural = "Dag Files"

class Dag_Task(models.Model):
    id = models.AutoField(primary_key=True)
    dag = models.ForeignKey('DAG', on_delete=models.SET_NULL, null=True)
    execute_at_ts = models.DateTimeField()
    parameter = models.CharField(max_length=100, null=True, blank=True)
    created_ts = models.DateTimeField(auto_now_add=True)
    executed_at_ts = models.DateTimeField(null=True, blank=True)
    updated_at_ts = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    def __str__(self):
        return f'{self.id}'
    
    class Meta:
        verbose_name = "Dag Task"
        verbose_name_plural = "Dag Tasks"
        ordering = ['-updated_at_ts']
        


class Files(models.Model):
    id = models.AutoField(primary_key=True)
    dag_task = models.ForeignKey('Dag_Task', on_delete=models.SET_NULL, null=True)
    dag_file = models.ForeignKey('Dag_File', on_delete=models.SET_NULL, null=True)
    path = models.FileField(upload_to=path_and_rename, validators=[validate_for_csvfile_type])
    created_ts = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    history = HistoricalRecords()

    def __str__(self):
        return f'{self.path}'
    
    class Meta:
        verbose_name = "Files"
        verbose_name_plural = "Files"
        ordering = ['-created_ts']

class Dag_Runs(models.Model):
    id = models.AutoField(primary_key=True)
    dag_task = models.ForeignKey(Dag_Task, on_delete=models.SET_NULL, null=True, blank=True)
    created_ts = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    airflow_dag_run_id = models.CharField(max_length=100, null=True, blank=True)
    airflow_dag_run_status = models.CharField(max_length=100, null=True, blank=True)
    message = models.CharField(max_length=1000, null=True, blank=True)
    history = HistoricalRecords()

    class Meta:
        ordering = ['-created_ts']

dataeng/forms.py
from django import forms
 
from .models import DataEng

class DataEngForm(forms.ModelForm):
    class Meta:
        model = DataEng
        fields = ['id', 'task', 'params', 'attachment']

rover/forms.py
from django import forms
from .models import *
from django.forms.models import inlineformset_factory

class DagTaskFilesCreateForm(forms.ModelForm):
    
    class Meta:
        model = Files
        exclude = ()

DagTaskFilesCreateFormSet = inlineformset_factory(
    Dag_Task # parent
    , Files # child
    , form = DagTaskFilesCreateForm
    , extra = 1
    , can_delete = False
)

dataeng/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, View
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.templatetags.static import static
import requests
from django.conf import settings
import json
from django.utils import timezone
from datetime import datetime
from django.http import JsonResponse

from .forms import DataEngForm
from .models import DataEng, TaskName

HBB_CENTRAL_URL = settings.HBB_CENTRAL_URL

# Create your views here.
class TasksView(LoginRequiredMixin, ListView):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    model = DataEng
    template_name = 'dataeng/tasks.html'
    context_object_name = 'tasks'

@login_required
def createTask(request):
    if request.method == 'POST':
        form = DataEngForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('tasks')
    else:
        form = DataEngForm()
    return render(request, 'dataeng/upload.html', {'form': form})

@login_required
def refreshTask(request, id):
    if request.method == 'GET':
        task = DataEng.objects.get(id=id)
        task_name = task.task.task_name
        params = task.params
        attachment = task.attachment
        refreshed = task.refreshed_at
        task_id = task.pk

        request_data = {}

        if params:
            args = json.loads(params) 
        else:
            args = {}

        if task_name:
            request_data['task'] = task_name
        
        if attachment:
            prefix = 'https://' if request.is_secure() else 'http://'
            file_url = prefix + request.get_host() + attachment.url
            args['file_path'] = file_url

        request_data['args'] = args

        r = requests.post(HBB_CENTRAL_URL + 'runtask', json=request_data)

        if r.status_code != 200:
            message = r.content
            print(message)
        else:
            data = r.json()
            task.task_scheduled_id = data.get('task_id', None)
            message = 'added to queue'        

        task.message = message
        task.refreshed_at = datetime.now(tz=timezone.utc)
        task.save()

    return redirect('tasks')

@login_required
def refreshTaskStatus(request, id):
    if request.method == 'GET':
        task = DataEng.objects.get(id=id)
        task_scheduled_id = task.task_scheduled_id
        r = requests.get(HBB_CENTRAL_URL + 'runtask/' + task_scheduled_id)

        try:
            data = r.json()
            task_scheduled_status = data.get('message', None)
        except:        
            task_scheduled_status = r.content
        
        task.task_scheduled_status = task_scheduled_status
        task.save()

        # TODO: Create end point in hbb_central to run the tasks, save log and refreshed_at in table
    return redirect('tasks')

rover/views.py
from django.forms.utils import ErrorList
import requests
from .models import *
from .forms import *
from django.views.generic.edit import CreateView
from django.views.generic import ListView, DetailView
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.db import transaction
from datetime import datetime
from django.conf import settings
from django.utils import timezone
from .widgets import BootstrapDateTimePickerInput
from django.core import serializers
import json
from django.http import JsonResponse, HttpResponseRedirect
from requests.auth import HTTPBasicAuth 
from .airflow import trigger_dag, get_dagRun_status


def dagTaskPush(request, pk):
    if request.method == 'GET':
        dagTask = Dag_Task.objects.get(id=pk)
        dagFile = Files.objects.filter(dag_task_id = pk)

        file_data = {}
        for file in dagFile:
            prefix = 'https://' if request.is_secure() else 'http://'
            file_url = prefix + request.get_host() + file.path.url
            file_data[file.dag_file.name] = file_url

        if dagTask.parameter:
            parameter = json.loads(dagTask.parameter)
        else:
            parameter = {}
        
        conf = {
                "parameters": parameter
                , "files": file_data
            }
        
        airflow_resp = trigger_dag(dagTask.dag.name, conf)
        try:
            airflow_resp.raise_for_status()
            data = airflow_resp.json()
            Dag_Runs.objects.create(dag_task_id=pk, airflow_dag_run_status=data['state'], airflow_dag_run_id=data['dag_run_id'])
        except Exception:
            Dag_Runs.objects.create(dag_task_id=pk, message='Failed to trigger dag')

        return redirect('dagtask_view', pk=pk)

def dagTaskStatus(request, pk):
    if request.method == 'GET':
        dagRun = Dag_Runs.objects.get(id=pk)
        dagTask = Dag_Task.objects.get(pk=dagRun.dag_task_id)
        dagName = dagTask.dag.name
        dag_run_id = dagRun.airflow_dag_run_id

        r = get_dagRun_status(dagName, dag_run_id)

        try:
            data = r.json()
            Dag_Runs.objects.filter(pk=pk).update(airflow_dag_run_status=data['state'])
        except Exception as e:
            print(r.status_code, r.content, e)

        return redirect('dagtask_view', pk=dagTask.id)


class DagTask(ListView):
    model = Dag_Task
    template_name = 'rover/dag_task.html'
    context_object_name = 'dag_task'

class DagTaskView(DetailView):
    model = Dag_Task
    template_name = 'rover/dag_task_detail.html'   
    context_object_name = 'dag_task' 
    def get_context_data(self, **kwargs):
        data = super(DagTaskView, self).get_context_data(**kwargs)
        pk = self.kwargs['pk']
        data['files'] = Files.objects.filter(dag_task_id = pk )
        data['dag_runs'] = Dag_Runs.objects.filter(dag_task_id = pk )
        return data


class DagTaskCreate(CreateView):
    # https://medium.com/@adandan01/django-inline-formsets-example-mybook-420cc4b6225d
    model = Dag_Task
    template_name = 'rover/dag_task_form.html'
    fields = ['dag', 'execute_at_ts', 'parameter']

    def get_context_data(self, **kwargs):
        data = super(DagTaskCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['dagtaskfiles'] = DagTaskFilesCreateFormSet(self.request.POST
                , self.request.FILES
                , instance=self.object)
        else:
            data['additional_data'] = json.dumps({
                "dag_file": serializers.serialize('json', DAG.objects.all())
                , "files": serializers.serialize('json', Dag_File.objects.all())
            })
            data['dagtaskfiles'] = DagTaskFilesCreateFormSet()
            # print(data)
        return data
    
    def form_valid(self, form):
        context = self.get_context_data()
        dagtaskfiles = context['dagtaskfiles']
        with transaction.atomic():
            self.object = form.save()
            if dagtaskfiles.is_valid():
                dagtaskfiles.instance = self.object
                dagtaskfiles.save()
        return super(DagTaskCreate, self).form_valid(form)
    
    def get_form(self, form_class=None):
        form = super(DagTaskCreate, self).get_form(form_class)
        form.fields['execute_at_ts'].widget = forms.DateTimeInput(
            attrs={'class':'datepicker', 'value': datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        )
        return form
    
    def get_success_url(self):
        return reverse('dagtask_view', kwargs={'pk': self.object.pk})

data_eng/templates/rover/dag_task.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Data Eng | Dag Tasks{% endblock %}

{% block content %}
    <div class="container">
        <h1>Dag Tasks</h1>
        <div>
            <a href="{% url 'dagtask_create' %}" class="btn btn-info" role="button">Create Task</a>
            <hr>
        </div>
        <div class="col-md-8">
            <table id="tasksTable" class="table">
                <thead class="table-light">
                    <th scope="col">Dag</th>
                    <th scope="col">Parameters</th>
                </thead>
                <tbody>
                    {% if dag_task %}
                    {% for task in dag_task %}
                    <tr id="task-{{}task.if}">
                        <th scope="row"><a href="{% url 'dagtask_view' pk=task.id %}">{{ task.dag}}</a></th>
                        <th scope="row">{{ task.parameter}}</th>
                    </tr>
                    {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

data_eng/templates/rover/dag_task_detail.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
<div class="container">
    <h3>Dag Task - {{ object.id }}</h3>
    <p><strong>Dag:</strong> <a href="#">{{ object.dag }}</a></p>
    <p><strong>Created At:</strong> <a href="#">{{ object.created_ts }}</a></p>
    <p><strong>Execute At:</strong> <a href="#">{{ object.execute_at_ts }}</a></p>
    <p><strong>Executed At:</strong> <a href="#">{{ object.executes_at_ts }}</a></p>
    <p><strong>Parameters:</strong> <a href="#">{{ object.parameter }}</a></p>
    <table class="table">
        <thead class="table-light">
            <th scope="col">Dag Files Uploaded</th>
        </thead>
        <tbody>
            {% for file in files %}
            <tr>
                <th scope="row"><a href="{{ file.path.url}}" target="_blank" rel="noopener noreferrer">{{ file.dag_file }}</a></td>
                <td></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h3>Dag Runs</h3>
    <table class="table">
        <thead class="table-light">
            <th scope="col">Created</th>
            <th scope="col">Airflow Dag Run #</th>
            <th scope="col">Status</th>
            <th scope="col">Message</th>
        </thead>
        <tbody>
            {% for run in dag_runs %}
            <tr>
                <th scope="row">{{ run.created_ts }}</td>
                <th scope="row">{{ run.airflow_dag_run_id }}</td>
                <th scope="row">{{ run.airflow_dag_run_status }}</td>
                <th scope="row">{{ run.message }}</td>
                {% if run.airflow_dag_run_id %}
                    <th scope="row"><a type = 'button' class="btn btn-warning" href="{% url 'dagtask_status' pk=run.id %}">Refresh</a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <row>
        <a type = 'button' class="btn btn-warning" href="{% url 'dagtask' %}">Back</a>
        <a href="{% url 'dagtask_refresh' pk=object.id %}" class="btn btn-info" role="button">Run Again</a>
    </row>
</div>
{{ object.title }}
{{ file.path.url}}
{% endblock %}

data_eng/templates/rover/dag_task_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}DataEng | Dag Tasks{% endblock %}
{% block content %}
<div class="container">
    <h3>Create Dag Task</h3>
    <hr>
<div class="col-md-8">
    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <hr>

        <table class="table" id="dag_files_form">
            {{ dagtaskfiles.management_form }}
            {% for form in dagtaskfiles.forms %}
                {% if forloop.first %}
                    <thead>
                    <tr>
                        {% for field in form.visible_fields %}
                            {{ field.errors.as_ul }}
                            <th>{{ field.label|capfirst }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                {% endif %}
                <tbody id="items-form-container">
                </tbody>
            {% endfor %}
            
        </table>
        <row >
            <button id="submit_row" type="submit" class="hidden btn btn-primary">Submit</button>
            <a type = 'button' class="btn btn-warning" href="{% url 'dagtask' %}">Cancel</a>
            
        </row>
    </form>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static 'formset/jquery.formset.js' %}"></script>
<script type="text/html" id="item-template">
    <tr>
        {% for field in dagtaskfiles.empty_form.visible_fields %}
        <td>
            {{ field }}
        </td>
    
        {% endfor %}
    </tr>
        
</script>
<script type="text/javascript">
    var additional_data = JSON.parse('{{additional_data|escapejs}}');
    $('#dag_files_formset').formset({
        prefix: '{{ dagtaskfiles.prefix }}',
        addText: 'Add'
    });

    document.querySelector('#id_dag').addEventListener("change", function(){
        var id_selected = this.value;
        get_dag_files(id_selected)
    })

    function get_dag_files(id){
        var dag_file = JSON.parse(additional_data['dag_file']);
        var file_list = dag_file.filter(i => i['pk'] == id)[0]['fields']['file_list'];
        var files = JSON.parse(additional_data['files'])
        var files_filtered = files.filter(i => file_list.includes(i['pk']))

        document.querySelector('#items-form-container').innerHTML = ""

        for (var i=0; i<files_filtered.length; i++){
            var pk = files_filtered[i]['pk']
            var item_name = files_filtered[i]['fields']['name']
            addItem()
            document.querySelectorAll('#items-form-container select')[i].innerHTML = ""
            document.querySelectorAll('#items-form-container select')[i].innerHTML = '<option value="'+ pk + '" selected>'+ item_name + '</option>'
            document.querySelectorAll('#items-form-container input')[i].setAttribute("required", "")
            // document.querySelectorAll('#items-form-container select')[i].options[pk].selected = true;
            // document.querySelectorAll('#items-form-container select')[i].options[pk].selected = "selected";
            // document.querySelectorAll('#items-form-container select')[i].value = pk;
            // document.querySelectorAll('#items-form-container select')[i].selectedIndex  = pk;
            // $('#items-form-container select')[i].selectedIndex  = pk;
            // document.querySelectorAll('#items-form-container select')[i].disabled = true;
        }

        $('#submit_row').removeClass('hidden')

    }
    

    function addItem(){
        
        var count = $('#items-form-container').children().length;
        var tmplMarkup = $('#item-template').html();
        var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);

        $('#items-form-container').append(compiledTmpl);
        
        // update form count
        $('#id_{{ dagtaskfiles.prefix }}-TOTAL_FORMS').attr('value', count+1);
    };    

</script>
{% endblock content %}